### PR TITLE
Add /all handler for printing or exporting slides as PDF

### PR DESCRIPTION
**Pull request by tstromberg**
Some places, such as KubeCon, require a PDF ahead of time of your presentation.

It may not be ideal, but it works and acts as a conversation starter. What should I do with it?

### CODE REVIEW

**Comment by dgageot** [comment]
Hey @tstromberg!
I've had a PR to support PDF export waiting to be finished for quite some time. You PR motivated me to finish it. Tell me if that's something you could use: https://github.com/dgageot/demoit/pull/51

**Comment by tstromberg** [comment]
This is exactly what I wanted for KubeCon. Thank you!

**Comment by dgageot** [comment]
Hey @tstromberg, I'm not sure what's going on on this PR ;-)

**Comment by Deleplace** [comment]
@dgageot It's about merging a talk about Minikube into DemoIt \o/
Shan't we make this happen?

**Comment by dgageot** [comment]
Hey @tstromberg I'm going to close this PR since I think it was pushed here by error

**Pull request closed without merging**
